appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32977cd1578b0700304c21
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: H2sj+xkPJnbWXipmxme5fHFSXUsGPRKTsjTw2OAD2f/Y3fK3Qpt3302A3U/d8cQtLVu0vrqoG3nmeJyEgQDYpVUu3Bx/BBdfWCGu0aBy8LqYgtb6pA3QbAA8qepXwzIpnDMnaVjnkiA6YdBDA0sy74dnMYf1Eg2m4sn8VS5q0N1rXf5gl66SxKFKIGBd4GkrgMH+G4EFq5ru1XTyZtTlAnpF5HuEgTomLo7vrFuiJyv/0EiGf/tHXo6SOSkBaT5hakPrvVnHFkrGW+G2cRXsqeBCdoV4kpoQdyTJX2wk/ZUCmBr+xecEOsX2NPgecaDHfWbClL0VLYMoEk1Gg5y1GPjFdimAt5g+naDGW8Ggs0IVcXVWMRF7y6rb8o8XcStFMwgMt3MQ+E+hGMPkNO0LeKFeR85Au88QiSDU/F/+q6JsxaR9Wzm19L3a8CvXElvBzOqa2WA98mQDK0mzUI4rE4aiJlxwfXAxZSeFiY/ZadRMFfCVTnfAm4f40TRZ7Ntqy2KIW0RyvW0XoW68ylF696Jt8wCrguLmsBwL6l8v5HCrXyjXW61rym817G97m/Gvj0QQ0C1Io5hKBOybD4ytOk+y0c8Y8+jhtIkO/qVw16sqlS0Et0RDzoaiwG4BSIsAEoJkkwzkCVO+o6ZkX4eox00UkH3h7+vc16Ci7hnqPXk=}
